### ISSUE TITLE
BagLinter fails on fetch files that are listed in the manifest file

### ISSUE THREAD

**Issue by rvanheest** [LibraryOfCongress/bagit-java#117]
_I'm currently using version 0.97 of the BagIt File Packaging Format together with bagit-java, but this issue may probably also occur in other versions such as v1.0._

My bag is as follows:

```
bag/
  |
  + - data
  |    |
  |    + - y
  |
  + - bag-info.txt
  |
  + - bagit.txt
  |
  + - fetch.txt
  |
  + - manifest-sha1.txt
  |
  + - tagmanifest-sha1.txt
```

with `fetch.txt` as follows:

```
http://localhost/data/sub/u  12  data/sub/u
http://localhost/data/sub/v  12  data/sub/v
http://localhost/data/y  12  data/y-old
http://localhost/data/x  12  data/x
```

and both `data/y` and all files in `fetch.txt` listed in `manifest-sha1.txt`:

```
1abd6cc24e13fa2ad36a621bf7fd94de26a6701a  data/x
f3308597f8772277b3e43678831e7cc7ab732789  data/y
331a69099835c3c4d3769fe287d67d04a7aea0da  data/y-old
26df90e63843325578e5242a08db8f1e2abcf179  data/sub/v
36e74ac7f74e4969a46209adcb311563bafb1a05  data/sub/u
```

When I run `BagLinter.lintBag(bag.path)` on this bag, I get a `NoSuchFileException` on `bag/data/sub` from `BagLinter`/`ManifestChecker`:

```
java.nio.file.NoSuchFileException: ***/***/bag/data/sub
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at gov.loc.repository.bagit.conformance.ManifestChecker.checkNormalization(ManifestChecker.java:147)
	at gov.loc.repository.bagit.conformance.ManifestChecker.checkData(ManifestChecker.java:93)
	at gov.loc.repository.bagit.conformance.ManifestChecker.checkManifests(ManifestChecker.java:54)
	at gov.loc.repository.bagit.conformance.BagLinter.lintBag(BagLinter.java:131)
	at gov.loc.repository.bagit.conformance.BagLinter.lintBag(BagLinter.java:93)
``` 

Ultimately this boiles down to the `ManifestChecker` trying to open a [`newDirectoryStream`](https://github.com/LibraryOfCongress/bagit-java/blob/61c50c841cebcbdcea886943bb17adc7adbc9664/src/main/java/gov/loc/repository/bagit/conformance/ManifestChecker.java#L147) on `bag/data/sub`, which doesn't actually exist on the file system, but only 'virtually' due to `fetch.txt`. In that sense it seems like the `BagLinter` doesn't take `fetch.txt` into account.

While I tested this with v0.97, I suspect this is also the case in v1.0. The former spec doesn't specify whether files listed in `fetch.txt` should be in the manifest file(s) as well (and therefore you might agrue that this exception is 'somewhat correct'), but the latter spec does specify that [explicitly](https://tools.ietf.org/html/draft-kunze-bagit-16#section-2.2.3) ("_Every file listed in the fetch file MUST be listed in every payload manifest._"; see also #116). From that point of view, I would not expect to see the `BagLinter` fail here.

**Comment by johnscancella** [comment]
`BagLinter` does not verify a bag (this is mentioned in the documentation string on `BagLinter.lintBag` (see http://www.javadoc.io/doc/gov.loc/bagit/5.1.1)

In my personal opinion fetch files should be avoided whenever possible and are a crude hack based from a time when sending a complete bag was much harder due to small storage sizes.

With that being said, it should probably fail more gracefully and I will update it to do so.

**Comment by rvanheest** [comment]
Awesome! I look forward to the fix.

> (...) fetch files should be avoided whenever possible

Not sure if I agree. In my organisation we use Bags to archive data in a structured way ([check out our documentation on 'Additional Packaging Requirements'](https://easy.dans.knaw.nl/doc/sword2.html)) and particularly use `fetch.txt` to avoid storing data twice. When a revision of a dataset (a.k.a.) comes in, we compare it with all previous versions to see if files are the same. If so, we 'prune' the new revision and point to that file in an earlier revision using the `fetch.txt` file. When talking about datasets with a couple large files, this can already save us a couple gigabytes!
Also some clients of us use it to make the bags they send to us smaller by referring to unchanged files from previous revisions.
I agree that the way it's done is quite a hack, but we definitely like the feature itself!

**Comment by johnscancella** [comment]
@rvanheest While people have used bagit for archiving, I tend to think of it more as a transfer protocol. Once you get the data that is in the bag, I would recommend you store it in a proper object store(something like https://www.swiftstack.com/ or https://ceph.com/) that has de-duplication and provides much stronger guarantees than a pure hard drive. Bit rot is a real thing, so having software manage it should be considered a best practice especially when there exists off the shelf software

**Comment by johnscancella** [comment]
once the `version1` branch is merged and a new version is released this should be fixed. See https://github.com/LibraryOfCongress/bagit-java/commit/6f98716287b8f9a9158963814358b8ca3f8a5759

**Comment by johnscancella** [comment]
While working on this you run into a bit of a "chicken and the egg" problem because if you try and check the file is there you need to do some normalization, but you can't if the file isn't there...

So instead I am going to update the documentation to make it clear that you can only lint a `valid` bag and if you try it on an un-validated bag you might get an `IOException`

**Comment by rvanheest** [comment]
@johnscancella Would you mind taking another look at this? After upgrading to v1.2.0 of this libary, the original problem still exists.

In my `fetch.txt` file, I list a file that is mapped to `data/sub/v`, while `data/sub` does not yet exist (because all files in `sub` are listed in `fetch.txt`). According to [BagIt v16](https://tools.ietf.org/html/draft-kunze-bagit-16) this is a valid bag, since I've added all files listed in `fetch.txt` in all available payload manifests. This is in accordance with [section 2.2.3 of the spec](https://tools.ietf.org/html/draft-kunze-bagit-16#section-2.2.3):

> Every file listed in the fetch file MUST be listed in every payload manifest.

Hence we get

```
// ... all other checksums for manifest-sha1.txt
26df90e63843325578e5242a08db8f1e2abcf179  data/sub/v
```

So far so good. The `BagVerifier` is completely happy, hence your previously mentioned '_you can only lint a `valid` bag_' should apply. However, still the `BagLinter` fails with a `NoSuchFileException` as described in my initial post.

`checkNormalization` still wants to create a `Files.newDirectoryStream` from the `dirToCheck` directory (which in my case equates to `data/sub`, which does not exist, since all files in `data/sub` are listed in `fetch.txt`), which obviously still fails.

I'm not sure what you meant exactly with the 'chicken and egg' problem. To me it seems that you can just simply do a `Files.exists(dirToCheck)` somewhere in the code below.

https://github.com/LibraryOfCongress/bagit-java/blob/97a677004200cf120df4524695bf0ed139a081c0/src/main/java/gov/loc/repository/bagit/conformance/ManifestChecker.java#L191-L197

An even better solution might be to only do certain checks in `checkManifestPayload` when the file is not listed in `fetch.txt` (a.k.a. is present in the `bag/data` directory).
